#
## Setup XDG folders
#

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share


#
## Style variables
#

if [[ $XDG_CURRENT_DESKTOP != KDE ]]
then
	export QT_QPA_PLATFORMTHEME=gtk3
	export WINIT_UNIX_BACKEND=x11
	export TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1
fi


#
## Zsh history
#

HISTFILE=$XDG_CACHE_HOME/zsh_history

# Number of lines the shell remembers
HISTSIZE=2500

# Number of lines the history file stores
SAVEHIST=2000


#
## Environment
#

# Set editors
export EDITOR=nvim

# Find gui
programs=("neovide" "nvim-qt" "gnvim" "goneovim" "kitty nvim" "alacritty -e nvim")

for candidate in "${programs[@]}"
do
	if (command -v "$(echo $candidate | cut -d" " -f1)" &> /dev/null)
	then
		export VISUAL=nvim-gui
		export NVGUI="$candidate"
		break
	fi
done

# Add rust cargo to PATH
if [[ -e $HOME/.cargo/bin ]]
then
	export PATH=$HOME/.cargo/bin:$PATH
fi

# Add my programs and pip's to PATH
export PATH=$HOME/.local/bin:$PATH

# Add nix packages
if [[ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]]
then
	. $HOME/.nix-profile/etc/profile.d/nix.sh
fi

# Add parser combinators to Scala
export SCALACLASSPATH=$HOME/.local/lib/scala-parser-combinators_2.13-2.1.0+29-f2f0b4f8-SNAPSHOT.jar

